<% @base = "dc=test,dc=com" %>

test: &TEST
  host: <%= "localhost" %>
  port: 3389
  attribute: cn
  base: <%= "ou=people,#{@base}" %>
  admin_user: <%= "cn=admin,#{@base}" %>
  admin_password: secret
  ssl: false

development:
  <<: *TEST
